/*
 * Documentation...
 */

#ifndef SORTINGMATRICESHOMEWORK1_SORTING_ALGORITHMS_H
#define SORTINGMATRICESHOMEWORK1_SORTING_ALGORITHMS_H
#endif //SORTINGMATRICESHOMEWORK1_SORTING_ALGORITHMS_H

void insertion_sort(int* array, int n);